### ISSUE TITLE
Creating collection from multi-dimensional JSON fails

### ISSUE THREAD

**Issue by ConneXNL** [AmpersandJS/ampersand-collection#11]
When initializing a collection from a multidimensional json, any sub collections will have an empty model as its first value in the sub collection. An empty collection will even contain 1 empty object in the collection.

For example, 

var schools = [{
  "school_name" : "A",
  "students" : []  
},{
  "school_name" : "B"
  "students" : [{"name" : "Lance"}] 
}];

new SchoolCollection(schools);

Will result in the student collection having an empty object for school A.
School B's student collection will contain an empty object and the object for Lance.

**Comment by HenrikJoreteg** [comment]
this has been documented for a while, closing. #cleaningupissues
