### ISSUE TITLE
Tests can't be run through tape-run with phantomjs

### ISSUE THREAD

**Issue by lukekarrys** [AmpersandJS/ampersand-collection#23]
It'd be nice if tests could be run like this: `browserify test/* | tape-run | tap-spec`, but they fail on the `isCollection` immutable test because of this phantomjs bug: https://github.com/ariya/phantomjs/issues/11856

Not high priority, but just a marker for when phantomjs fixes that bug.

**Comment by wraithgar** [comment]
Oh hey looks like I fixed this. Hi Luke, hope all is well with you today.

**Comment by lukekarrys** [comment]
:wave: :smile:
