### ISSUE TITLE
Fix performance issues in collections and subcollections

### ISSUE THREAD

**Issue by wraithgar** [AmpersandJS/ampersand-collection#44]
Currently `collection.indexOf` and everything about subcollections is very inefficient.  Normally you don't see this problem in collections (indexOf isn't used on orders of magnitude that cause problems for most people), however in subcollections the problem becomes quickly untenable for collections even nearing a hundred items.

After a lot of hacking and testing, I (with a lot of help from @legastero and @latentflip) have decided that a new approach is needed.  This issue is for outlining that approach, with hopefully minimal feedback.  I would kindly ask that until we have an actual proposal ironed out we keep debate and discussion to a minimum. (i.e. this has to get to even a certain point before we're ready to enter a wider discussion).

This issue will be mostly about visibility with the @AmpersandJS/core-team as we work through the problem.

If you would like to see a quick demo of the problem, run this artifice.danger.computer/ubavuzoxek.js but note that the devDependency for ampersand-model is pre@1.0.0 so you'll have to update that to remove `isNew` errors.

**Comment by wraithgar** [comment]
Currently the thinking is:

- Make a new base collection module that powers collections and subcollections called indexed-list
- Break subcollections out into two modules `ampersand-paged-collection` and `ampersand-filtered-collection` (subcollection can combine these and maintain its current api)

indexed-list will need to maintain both its current named indexing of models (to deal with add/update duplication checks etc) as well as a new offset index (to make indexOf a quick lookup).  We need a fast indexOf for most of the things subcollection does (for instance determining if an event needs to bubble up i.e. is this model now a part of the new subcollection).  It would still maintain an array of models so that the current exposed array methods would still all work, and also so that subcollections could easily paginate.

There is a branch in subcollection called `performance` that contains the current wips of getting some of the optimizations ironed out. This branch will likely never be merged in, it's a sandbox for sharing code between those who are working on this problem.

paged-collection would take limit/offset and then slice its parent
filtered-collection would apply a filter to its parent, maintaining parent order unless overridden by its own comparator.

**Comment by wraithgar** [comment]
indexed-list `add` would need to use a binary-search + comparator to find the intended index of the new model. Current javascript sorting functions do not allow us to know where our items ended up without a second complete iteration through the list.

This will make all adds with a comparator O(log n) speed (adds without a comparator are simpler of course).

**Comment by legastero** [comment]
If we have `ampersand-paged-collection`, we really don't need that to emit anything other than `reset` events. Something changed? Throw out everything, reslice and emit 'reset'. Any collection view will have the existing item views cached. If it is still slow then, there's really not much we can do. Caveat emptor.

We already made the filtered collection fast in the peformance branch: it was trying to maintain indexes after slicing for paging that was the still-be-solved problem.

**Comment by wraithgar** [comment]
So performance branch can become ampersand-filtered-collection and then subcollection can intelligently tie them together.

**Comment by wraithgar** [comment]
Here is paged collection https://github.com/wraithgar/paged-collection

Discussion is now open and welcome for that repo, we can move it to this org as ampersand-paged-collection if we like it.

**Comment by wraithgar** [comment]
Here is filtered collection https://github.com/wraithgar/filtered-collection

Discussion is now open and welcome for that repo, we can move it to this org as ampersand-filtered-collection if we like it.

**Comment by wraithgar** [comment]
These two PRs are required for this project https://github.com/AmpersandJS/amp/pull/76 https://github.com/AmpersandJS/amp/pull/74

**Comment by wraithgar** [comment]
Here are the performance metrics http://artifice.danger.computer/perusinuve.txt

**Comment by imlucas** [comment]
@wraithgar any updates on this?  I've been quite curious about perf & tracking perf over time for `ampersand-collection` for quite a bit.  Has there been any discussion about switching the under-the-hood manipulation to use [crossfilter](https://github.com/square/crossfilter), [pourover](https://github.com/NYTimes/pourover), [ndarray](http://npm.im/ndarray) or the like?

**Comment by wraithgar** [comment]
@imlucas a great deal of effort was put into refactoring subcollection which resulted in https://github.com/AmpersandJS/ampersand-filtered-subcollection and https://github.com/AmpersandJS/ampersand-paginated-subcollection.  Currently ampersand-collection doesn't have any plans for more optimization.  I'll be closing this as it was primarily about the subcollection performance issues (which were huge).  If there is a specific performance problem w/ collection please open a new issue to discuss it since this one's run its course.
