### ISSUE TITLE
using ES5 `bind` for double argument comparator causes Phantom.js to fail

### ISSUE THREAD

**Issue by mmacaula** [AmpersandJS/ampersand-collection#52]
Just ran across this one, and thought I'd share in case others are searching.  Could be easily fixable, but I could understand why it wouldn't be.

On [this line](https://github.com/AmpersandJS/ampersand-collection/blob/master/ampersand-collection.js#L240) the native `.bind` is being used to bind the comparator to `this`.  This only happens on a multi-argument comparators: `comparator : function(a, b){}`.  

This causes phantom js (using ~1.9.7-1) to fail unfortunately.  While that's not really ampersand's concern, this could be modified to use lodash .bind or amp `.bind`.  This seems to be the approach in `ampersand-state` where underscore.bind is used. 

I'd be happy to submit a PR to fix, using amp .bind if desired. 

We were able to fix by loading es5.shim in phantom for those who run into similar issue.

**Comment by chesles** [comment]
I ran into the same issue the other day - you just need a polyfill for `Function.prototype.bind`, because phantomjs 1.9.x doesn't define it. I've been including this package: https://www.npmjs.com/package/bindpolyfill

**Comment by wraithgar** [comment]
This is fixed in v1.4.1
