### ISSUE TITLE
Upgrade from 1.4.2 to 1.4.3 causes jasmine tests to fail

### ISSUE THREAD

**Issue by jasonrose** [AmpersandJS/ampersand-collection#56]
I'm going to try to get a test case this weekend, but I don't know if I will be able to reproduce the environment.

My karma/jasmine unit tests pass with `ampersand-collection` 1.4.2 but time out 100% of the time when using 1.4.3.  I think that the reindex code is hitting an infinite loop or is causing too many cascading operations.

**Comment by bear** [comment]
@lukekarrys can you look at this when you get a chance - the merge for 1.4.3 shows only a single PR since 1.4.2

**Comment by lukekarrys** [comment]
@jasonrose I will look into this also. Thanks for pointing us the in right direction with the infinite loop + cascading operations stuff. Both those things would make sense with how the new index code works I think.

**Comment by latentflip** [comment]
Fixed in 1.4.4
