### ISSUE TITLE
Collection of Collections

### ISSUE THREAD

**Issue by boopathi** [AmpersandJS/ampersand-collection#60]
I need to use this as ampersand Model and collections.

```
[ // Collection1
  [ // ItemsCollection
    {}, //ItemModel
    {}
  ],
  [
    {},
    {}
  ]
]
```

Can I just use ? Is this a proper way to do it ?

```js
Collection.extend({
  model: ItemsCollection
});
```

**Comment by cdaringe** [comment]
Hey @boopathi:

You are on the right track!  I've created a detailed [requirebin for you to check out](http://requirebin.com/?gist=d514a6c2c6ee92095253) that shows a couple ways to do this.   Open up your console and follow along with the code :)  Come back and ask questions as needed.

:smile:

**Comment by boopathi** [comment]
Thanks!, That works, but got some doubts. 

http://requirebin.com/?gist=a46ac911db1e67a558f8 

In the example2 in that gist, when I pass the data directly, it'll be an instanceof `Array` and not a `Collection`. So it throws.

I'm filling my root model from Top to Bottom. The data that I'm getting for the models is deep (depth=7,8 ), so I'm passing my entire data to a root model (ampersand-state), and everything except using a collection in collection works fine. 

Is there any workaround, say modifying the model object in isModel ?

```js
isModel: function(model) {
  if(Array.isArray(model)) model = new ItemsCollection(model);
  return true;
}
```

**Comment by cdaringe** [comment]
Yeah, the interface isn't designed to handle such an approach. The & strategy is generally one of minimalism and simplicity, meaning, that it won't go create that nested data structure on your behalf or allocate that memory on your behalf.  Perhaps, you could write a small little interface object that does I/O on your nested collections, and creates the structures if they are not present?
